# Generated by Django 4.2 on 2025-01-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'm_pegawai',
            },
        ),
    ]
