# Generated by Django 4.2 on 2025-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
