# Generated by Django 4.2 on 2025-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_pegawai_jabatan_alter_pegawai_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
