# Generated by Django 4.2 on 2025-02-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('e-office', 'E-Office'), ('finger', 'Finger Print'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('waktu_masuk', models.TimeField(blank=True, null=True)),
                ('waktu_keluar', models.TimeField(blank=True, null=True)),
                ('jam_kerja', models.FloatField(blank=True, null=True)),
                ('absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.absensi')),
            ],
            options={
                'db_table': 'm_absensi_detail',
            },
        ),
    ]
