# Generated by Django 4.2 on 2025-02-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_pegawai_jabatan_alter_pegawai_nama'),
        ('absensi', '0002_absensidetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensidetail',
            name='pegawai',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai'),
        ),
    ]
