# Generated by Django 4.2 on 2025-04-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_absensi_jam_kerja_absensi_metode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='metode',
            field=models.CharField(choices=[('', '--PILIH METODE--'), ('e-office', 'E-Office'), ('finger', 'Finger Print'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='absensidetail',
            name='metode',
            field=models.CharField(choices=[('', '--PILIH METODE--'), ('e-office', 'E-Office'), ('finger', 'Finger Print'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
    ]
