# Generated by Django 4.2 on 2025-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tukin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_jabatan', models.IntegerField()),
                ('jumlah_tunjangan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'm_tukin',
            },
        ),
    ]
